### ISSUE TITLE
How can I humanize validating all schemas?

### ISSUE THREAD

**Issue by saulshanabrook** [cddr/integrity#17]
I am currently using `(use-fixtures :once schema.test/validate-schemas)` in my tests files. Is it possible to do something similar, but get more human readable output?

**Comment by cddr** [comment]
Sorry for not getting back to you sooner. I had a quick look at the code in schema. Looks like you'd need to make some changes in here

https://github.com/plumatic/schema/blob/c6b66316231b9c8164b6a8580389c7584091de88/src/clj/schema/macros.clj#L234-L235

I think that `error#` symbol there would hold something that `humanize` could operate on. I doubt they would accept a patch that does this though.
